name: build-and-release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: linux
            ext: ""
          - os: macos-latest
            artifact_name: macos
            ext: ""
          - os: windows-latest
            artifact_name: windows
            ext: ".exe"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install .
      - name: Build executable
        run: pyinstaller dedupe_ui.py --name dedupe-ui-${{ matrix.artifact_name }} --onefile
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dedupe-ui-${{ matrix.artifact_name }}
          path: dist/dedupe-ui-${{ matrix.artifact_name }}${{ matrix.ext }}

  release:
    name: Create release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Extract version
        run: echo "VERSION=$(grep -Po '(?<=^version = \")[^\"]*' pyproject.toml)" >> $GITHUB_ENV
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: v${{ env.VERSION }}
          files: dist/**
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
